startPage = https://passport.yandex.ru/auth/add/login
csvData_path = src/test_data/csvData.csv
csvTestData_path = src/test_data/csvTestData.csv

# browser = Firefox
# browser = Chrome
# browser = Edge